package com.mycompany.asyncreq.dao;
// Generated Apr 28, 2015 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tcommodities generated by hbm2java
 */
@Entity
@Table(name="tcommodities"
    ,catalog="mydb"
)
public class Tcommodities  implements java.io.Serializable {


     private Integer id;
     private Integer cmdC;
     private String cmdDescE;
     private Integer parent;
     private String cmdLongDescE;
     private Boolean isLeaf;
     private Integer aggrlevel;
     private Set<Ttradedata> ttradedatas = new HashSet<Ttradedata>(0);

    public Tcommodities() {
    }

    public Tcommodities(Integer cmdC, String cmdDescE, String cmdLongDescE, Boolean isLeaf, Integer aggrlevel/*, Set<Ttradedata> ttradedatas*/) {
       this.cmdC = cmdC;
       this.cmdDescE = cmdDescE;
       //this.parent = parent;
       this.cmdLongDescE = cmdLongDescE;
       this.isLeaf = isLeaf;
       this.aggrlevel = aggrlevel;
       //this.ttradedatas = ttradedatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cmdC")
    public Integer getCmdC() {
        return this.cmdC;
    }
    
    public void setCmdC(Integer cmdC) {
        this.cmdC = cmdC;
    }

    
    @Column(name="cmdDescE", length=2000)
    public String getCmdDescE() {
        return this.cmdDescE;
    }
    
    public void setCmdDescE(String cmdDescE) {
        this.cmdDescE = cmdDescE;
    }

    
    @Column(name="parent")
    public Integer getParent() {
        return this.parent;
    }
    
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    
    @Column(name="cmdLongDescE", length=45)
    public String getCmdLongDescE() {
        return this.cmdLongDescE;
    }
    
    public void setCmdLongDescE(String cmdLongDescE) {
        this.cmdLongDescE = cmdLongDescE;
    }

    
    @Column(name="IsLeaf")
    public Boolean getIsLeaf() {
        return this.isLeaf;
    }
    
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    
    @Column(name="Aggrlevel")
    public Integer getAggrlevel() {
        return this.aggrlevel;
    }
    
    public void setAggrlevel(Integer aggrlevel) {
        this.aggrlevel = aggrlevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tcommodities")
    public Set<Ttradedata> getTtradedatas() {
        return this.ttradedatas;
    }
    
    public void setTtradedatas(Set<Ttradedata> ttradedatas) {
        this.ttradedatas = ttradedatas;
    }




}


