package com.mycompany.asyncreq.dao;
// Generated Apr 28, 2015 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tcountries generated by hbm2java
 */
@Entity
@Table(name="tcountries"
    ,catalog="mydb"
)
public class Tcountries  implements java.io.Serializable {


     private int crCode;
     private String crName;
     private String crFullName;
     private Set<Ttradedata> ttradedatasForPtCode = new HashSet<Ttradedata>(0);
     private Set<Ttradedata> ttradedatasForRtCode = new HashSet<Ttradedata>(0);

    public Tcountries() {
    }

	
    public Tcountries(int crCode) {
        this.crCode = crCode;
    }
    public Tcountries(int crCode, String crName, String crFullName) {
       this.crCode = crCode;
       this.crName = crName;
       this.crFullName = crFullName;

    }
   
     @Id 

    
    @Column(name="crCode", unique=true, nullable=false)
    public int getCrCode() {
        return this.crCode;
    }
    
    public void setCrCode(int crCode) {
        this.crCode = crCode;
    }

    
    @Column(name="crName", length=45)
    public String getCrName() {
        return this.crName;
    }
    
    public void setCrName(String crName) {
        this.crName = crName;
    }

    
    @Column(name="crFullName", length=45)
    public String getCrFullName() {
        return this.crFullName;
    }
    
    public void setCrFullName(String crFullName) {
        this.crFullName = crFullName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tcountriesByPtCode")
    public Set<Ttradedata> getTtradedatasForPtCode() {
        return this.ttradedatasForPtCode;
    }
    
    public void setTtradedatasForPtCode(Set<Ttradedata> ttradedatasForPtCode) {
        this.ttradedatasForPtCode = ttradedatasForPtCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tcountriesByRtCode")
    public Set<Ttradedata> getTtradedatasForRtCode() {
        return this.ttradedatasForRtCode;
    }
    
    public void setTtradedatasForRtCode(Set<Ttradedata> ttradedatasForRtCode) {
        this.ttradedatasForRtCode = ttradedatasForRtCode;
    }




}


