package com.mycompany.asyncreq.dao;
// Generated Apr 28, 2015 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testimationcodes generated by hbm2java
 */
@Entity
@Table(name="testimationcodes"
    ,catalog="mydb"
)
public class Testimationcodes  implements java.io.Serializable {


     private int estCode;
     private String estDesc;
     private Set<Ttradedata> ttradedatas = new HashSet<Ttradedata>(0);

    public Testimationcodes() {
    }

	
    public Testimationcodes(int estCode) {
        this.estCode = estCode;
    }
    public Testimationcodes(int estCode, String estDesc, Set<Ttradedata> ttradedatas) {
       this.estCode = estCode;
       this.estDesc = estDesc;
       this.ttradedatas = ttradedatas;
    }
   
     @Id 

    
    @Column(name="estCode", unique=true, nullable=false)
    public int getEstCode() {
        return this.estCode;
    }
    
    public void setEstCode(int estCode) {
        this.estCode = estCode;
    }

    
    @Column(name="estDesc", length=45)
    public String getEstDesc() {
        return this.estDesc;
    }
    
    public void setEstDesc(String estDesc) {
        this.estDesc = estDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testimationcodes")
    public Set<Ttradedata> getTtradedatas() {
        return this.ttradedatas;
    }
    
    public void setTtradedatas(Set<Ttradedata> ttradedatas) {
        this.ttradedatas = ttradedatas;
    }




}


