package com.mycompany.asyncreq.dao;
// Generated Apr 28, 2015 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tquantityunits generated by hbm2java
 */
@Entity
@Table(name="tquantityunits"
    ,catalog="mydb"
)
public class Tquantityunits  implements java.io.Serializable {


     private Integer qtCode;
     private String qtDesc;
     private Set<Ttradedata> ttradedatas = new HashSet<Ttradedata>(0);

    public Tquantityunits() {
    }

    public Tquantityunits(Integer qtCode,String qtDesc/*, Set<Ttradedata> ttradedatas*/) {
        this.qtCode=qtCode;
       this.qtDesc = qtDesc;
       //this.ttradedatas = ttradedatas;
    }
   
     @Id 

    
    @Column(name="qtCode", unique=true, nullable=false)
    public Integer getQtCode() {
        return this.qtCode;
    }
    
    public void setQtCode(Integer qtCode) {
        this.qtCode = qtCode;
    }

    
    @Column(name="qtDesc", length=45)
    public String getQtDesc() {
        return this.qtDesc;
    }
    
    public void setQtDesc(String qtDesc) {
        this.qtDesc = qtDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tquantityunits")
    public Set<Ttradedata> getTtradedatas() {
        return this.ttradedatas;
    }
    
    public void setTtradedatas(Set<Ttradedata> ttradedatas) {
        this.ttradedatas = ttradedatas;
    }




}


