package com.mycompany.asyncreq.dao;
// Generated Apr 28, 2015 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tregimes generated by hbm2java
 */
@Entity
@Table(name="tregimes"
    ,catalog="mydb"
)
public class Tregimes  implements java.io.Serializable {


     private int rgCode;
     private String rgDesc;
     private Set<Ttradedata> ttradedatas = new HashSet<Ttradedata>(0);

    public Tregimes() {
    }

	
    public Tregimes(int rgCode,String rgDesc) {
        this.rgCode = rgCode;
       this.rgDesc = rgDesc;
    }
    public Tregimes(int rgCode, String rgDesc, Set<Ttradedata> ttradedatas) {
       this.rgCode = rgCode;
       this.rgDesc = rgDesc;
       this.ttradedatas = ttradedatas;
    }
   
     @Id 

    
    @Column(name="rgCode", unique=true, nullable=false)
    public int getRgCode() {
        return this.rgCode;
    }
    
    public void setRgCode(int rgCode) {
        this.rgCode = rgCode;
    }

    
    @Column(name="rgDesc", length=45)
    public String getRgDesc() {
        return this.rgDesc;
    }
    
    public void setRgDesc(String rgDesc) {
        this.rgDesc = rgDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tregimes")
    public Set<Ttradedata> getTtradedatas() {
        return this.ttradedatas;
    }
    
    public void setTtradedatas(Set<Ttradedata> ttradedatas) {
        this.ttradedatas = ttradedatas;
    }




}


